#Use the official python image from the DOcker Hub
FROM python:3.9-slim

#set the working directory
WORKDIR /app

#copy the current directory contents into the container at /app
COPY . /app


#install any needing packages  specified in requirements.txt
RUN pip install flask

#make port 5000 available to the world outside this container
EXPOSE 5000

#Run the appp.py when the container launches
CMD [ "python","app.py" ]